const { isAtsEnabledByDefault } = require("./adapter-metadata");

const ATS_FILTER_OPTION_ITEMS = Object.freeze([
  { value: "100hires", label: "100Hires" },
  { value: "aarkrecruiting", label: "Aark Recruiting" },
  { value: "abacushumanresources", label: "Abacus Human Resources" },
  { value: "accessrecruitmentportal", label: "Access Recruitment Portal" },
  { value: "acquiretalentaustralia", label: "AcquireTalent Australia" },
  { value: "adafacescreening", label: "Adaface Screening" },
  { value: "adcorpportal", label: "Adcorp Portal" },
  { value: "adeccoportal", label: "Adecco Portal" },
  { value: "adeccosingapore", label: "Adecco Singapore" },
  { value: "adp_myjobs", label: "ADP MyJobs" },
  { value: "adp_workforcenow", label: "ADP Workforce Now" },
  { value: "adway", label: "Adway" },
  { value: "adzunaats", label: "Adzuna ATS" },
  { value: "adzunaaustralia", label: "Adzuna Australia" },
  { value: "airachile", label: "Aira Chile" },
  { value: "airswiftportal", label: "Airswift Portal" },
  { value: "akhtabootjordan", label: "Akhtaboot Jordan" },
  { value: "akkencloud", label: "AkkenCloud" },
  { value: "alayacarehr", label: "AlayaCare HR" },
  { value: "allegisgroupportal", label: "Allegis Group Portal" },
  { value: "altamirarecruiting", label: "Altamira Recruiting" },
  { value: "alvalabs", label: "Alva Labs" },
  { value: "amropportal", label: "Amrop Portal" },
  { value: "apexrecruitment", label: "Apex Recruitment" },
  { value: "apli", label: "Apli" },
  { value: "applicantai", label: "ApplicantAI" },
  { value: "applicantpro", label: "ApplicantPro" },
  { value: "applicantstack", label: "ApplicantStack" },
  { value: "applied", label: "Applied" },
  { value: "applitrack", label: "Applitrack" },
  { value: "apploi", label: "Apploi" },
  { value: "applytojob", label: "ApplyToJob" },
  { value: "arbeitnow", label: "Arbeitnow" },
  { value: "aresrecruiting", label: "Ares Recruiting" },
  { value: "ashby", label: "Ashby" },
  { value: "atsondemand", label: "ATS OnDemand" },
  { value: "atsumarujapan", label: "Atsumaru Japan" },
  { value: "aurarecruitingbr", label: "Aura Recruiting BR" },
  { value: "auratalent", label: "Aura Talent" },
  { value: "aviont", label: "Avionté" },
  { value: "bamboohr", label: "BambooHR" },
  { value: "barraiser", label: "BarRaiser" },
  { value: "baytcommena", label: "Bayt.com MENA" },
  { value: "bayzatuae", label: "Bayzat UAE" },
  { value: "beaconhillportal", label: "Beacon Hill Portal" },
  { value: "beamery", label: "Beamery" },
  { value: "bearclawats", label: "Bear Claw ATS" },
  { value: "beckrecruitment", label: "Beck Recruitment" },
  { value: "beetween", label: "Beetween" },
  { value: "beetween_new", label: "Beetween" },
  { value: "beetweenfrance", label: "Beetween France" },
  { value: "berlinrecruiting", label: "Berlin Recruiting" },
  { value: "bestjobsroats", label: "BestJobs.ro ATS" },
  { value: "bewerbermanagementat", label: "Bewerbermanagement.at" },
  { value: "bewerberportal", label: "Bewerberportal" },
  { value: "bewerbungnet", label: "Bewerbung.net" },
  { value: "bewerbungschweiz", label: "Bewerbung-Schweiz" },
  { value: "bigredskyaustralia", label: "BigRedSky Australia" },
  { value: "bitebewerbermanager", label: "BITE Bewerbermanager" },
  { value: "bizneoats", label: "Bizneo ATS" },
  { value: "bizreachjapan", label: "Bizreach Japan" },
  { value: "bluearrowrecruitment", label: "Blue Arrow Recruitment" },
  { value: "bneempresas", label: "BNE Empresas" },
  { value: "bondadaptadaptux", label: "Bond Adapt (AdaptUX)" },
  { value: "boydenportal", label: "Boyden Portal" },
  { value: "brassring", label: "BrassRing" },
  { value: "breezy", label: "BreezyHR" },
  { value: "breezyme", label: "Breezy ME" },
  { value: "brightermondaykenya", label: "BrighterMonday Kenya" },
  { value: "brightmove", label: "BrightMove" },
  { value: "broadbean", label: "Broadbean" },
  { value: "bryq", label: "Bryq" },
  { value: "byteboard", label: "Byteboard" },
  { value: "c1brokerrecruiting", label: "C1 Broker Recruiting" },
  { value: "cadrena", label: "Cadrena" },
  { value: "calcareers", label: "CalCareers" },
  { value: "calipercorp", label: "Caliper Corp" },
  { value: "calopps", label: "CalOpps" },
  { value: "candidator", label: "Candidator" },
  { value: "canditech", label: "Canditech" },
  { value: "cantaloopegypt", label: "Cantaloop Egypt" },
  { value: "capitaresourcing", label: "Capita Resourcing" },
  { value: "careerjetats", label: "Careerjet ATS" },
  { value: "careerplug", label: "CareerPlug" },
  { value: "careerpuck", label: "CareerPuck" },
  { value: "careers24southafrica", label: "Careers24 South Africa" },
  { value: "careerspage", label: "CareersPage" },
  { value: "cascadehrrecruitment", label: "Cascade HR Recruitment" },
  { value: "catalystone", label: "Catalyst One" },
  { value: "cathoempresas", label: "Catho Empresas" },
  { value: "cegid", label: "Cegid" },
  { value: "cegidtalent", label: "Cegid Talent" },
  { value: "ceipal", label: "CEIPAL ATS" },
  { value: "charthophr", label: "ChartHop HR" },
  { value: "chaze", label: "Chaze" },
  { value: "cinode", label: "Cinode" },
  { value: "ciphrrecruitment", label: "CIPHR Recruitment" },
  { value: "clearcompany", label: "ClearCompany" },
  { value: "cleverconnect", label: "CleverConnect" },
  { value: "cleverconnectfrance", label: "CleverConnect France" },
  { value: "cleverstaff", label: "CleverStaff" },
  { value: "clockworkrecruiting", label: "Clockwork Recruiting" },
  { value: "coats", label: "COATS Staffing Software" },
  { value: "coderpadrecruiting", label: "Coderpad Recruiting" },
  { value: "coderspaceats", label: "Coderspace ATS" },
  { value: "cognologyaustralia", label: "Cognology Australia" },
  { value: "collagehr", label: "Collage HR" },
  { value: "compleoats", label: "Compleo ATS" },
  { value: "computrabajoempresas", label: "Computrabajo Empresas" },
  { value: "connexysnowbullhorn", label: "Connexys (now Bullhorn)" },
  { value: "contratando", label: "Contratando" },
  { value: "cornerstoneondemand", label: "Cornerstone OnDemand" },
  { value: "cornerstonesingapore", label: "Cornerstone Singapore" },
  { value: "coveto", label: "Coveto" },
  { value: "coview", label: "Coview" },
  { value: "coviewgermany", label: "Coview Germany" },
  { value: "cpjobshongkong", label: "CPJobs Hong Kong" },
  { value: "ctgoodlifehongkong", label: "CTgoodlife Hong Kong" },
  { value: "culinaryagents", label: "Culinary Agents" },
  { value: "cultjobssingapore", label: "Cultjobs Singapore" },
  { value: "curriculumcombr", label: "Curriculum.com.br" },
  { value: "cvat", label: "CVAT" },
  { value: "darwinboxindia", label: "Darwinbox India" },
  { value: "datacrowdrecruiting", label: "Datacrowd Recruiting" },
  { value: "datakariera", label: "Datakariera" },
  { value: "dayforcehcm", label: "Dayforce", enabledByDefault: false },
  { value: "deelrecruiting", label: "Deel Recruiting" },
  { value: "deltektalentacquisition", label: "Deltek Talent Acquisition" },
  { value: "devskiller", label: "Devskiller" },
  { value: "dhrglobalportal", label: "DHR Global Portal" },
  { value: "digitalrecruiters", label: "DigitalRecruiters" },
  { value: "dodajapan", label: "Doda Japan" },
  { value: "dossierrecruiting", label: "Dossier Recruiting" },
  { value: "doverai", label: "Dover AI" },
  { value: "ducknow", label: "Ducknow" },
  { value: "dvinci", label: "d.vinci" },
  { value: "dvincigermany", label: "D.vinci Germany" },
  { value: "easycruitnowtalentech", label: "EasyCruit (now Talentech)" },
  { value: "easyhrturkey", label: "EasyHR Turkey" },
  { value: "easyrecrue", label: "EASYRECRUE" },
  { value: "egonzehnderportal", label: "Egon Zehnder Portal" },
  { value: "eightfold", label: "Eightfold" },
  { value: "ejobsroats", label: "Ejobs.ro ATS" },
  { value: "elemannetats", label: "Eleman.net ATS" },
  { value: "elempleoempresas", label: "El Empleo Empresas" },
  { value: "elevatusjordan", label: "Elevatus Jordan" },
  { value: "eliterecruiting", label: "Elite Recruiting" },
  { value: "elmosoftwareaustralia", label: "ELMO Software Australia" },
  { value: "emapartnersportal", label: "EMA Partners Portal" },
  { value: "emapartnerssingapore", label: "EMA Partners Singapore" },
  { value: "employercombr", label: "Employer.com.br" },
  { value: "employmentofficeaustralia", label: "Employment Office Australia" },
  { value: "emply", label: "Emply" },
  { value: "emplydenmark", label: "Emply Denmark" },
  { value: "enboarderonboarding", label: "Enboarder onboarding" },
  { value: "engagesoftware", label: "Engage Software" },
  { value: "eploy", label: "Eploy" },
  { value: "eployats", label: "Eploy ATS" },
  { value: "erecruit", label: "Erecruit" },
  { value: "erecruiterpoland", label: "eRecruiter Poland" },
  { value: "erecruitingat", label: "E-Recruiting.at" },
  { value: "erecruitingch", label: "E-Recruiting.ch" },
  { value: "erecrutement", label: "E-Recrutement" },
  { value: "eskillplatform", label: "eSkill Platform" },
  { value: "evarecruiting", label: "Eva Recruiting" },
  { value: "evarecruitingmx", label: "Eva Recruiting MX" },
  { value: "evarecruitingsg", label: "Eva Recruiting SG" },
  { value: "exelare", label: "Exelare" },
  { value: "ezekiasearch", label: "Ezekia Search" },
  { value: "factorialhrspain", label: "Factorial HR Spain" },
  { value: "fasthrbrazil", label: "FastHR Brazil" },
  { value: "fasthrjapan", label: "FastHR Japan" },
  { value: "fasthrmx", label: "FastHR MX" },
  { value: "fasthrsg", label: "FastHR SG" },
  { value: "fastjobssingapore", label: "FastJobs Singapore" },
  { value: "fetcher", label: "Fetcher" },
  { value: "finanzrecruiting", label: "Finanz-Recruiting" },
  { value: "fircroftportal", label: "Fircroft Portal" },
  { value: "firefish", label: "Firefish" },
  { value: "flatchr", label: "Flatchr" },
  { value: "flatchrfrance", label: "Flatchr France" },
  { value: "flocareer", label: "FloCareer" },
  { value: "forasnaegypt", label: "Forasna Egypt" },
  { value: "fountain", label: "Fountain" },
  { value: "frankfurtrecruiting", label: "Frankfurt Recruiting" },
  { value: "freshteam", label: "Freshteam" },
  { value: "g2recruitmentgroup", label: "G2 Recruitment Group" },
  { value: "galehealthcarestaffing", label: "Gale Healthcare Staffing" },
  { value: "gatenbysandersonportal", label: "GatenbySanderson Portal" },
  { value: "gem", label: "Gem" },
  { value: "genterecrutei", label: "Gente Recrutei" },
  { value: "germantechats", label: "GermanTech ATS" },
  { value: "gestmax", label: "GestMax" },
  { value: "getro", label: "Getro" },
  { value: "giraffesouthafrica", label: "Giraffe South Africa" },
  { value: "gisrecruiting", label: "Gis Recruiting" },
  { value: "glassdoorsingapore", label: "Glassdoor Singapore" },
  { value: "glorri", label: "Glorri" },
  { value: "gohire", label: "GoHire" },
  { value: "gorecruit", label: "GoRecruit" },
  { value: "governmentjobs", label: "GovernmentJobs" },
  { value: "graderecruiting", label: "Grade Recruiting" },
  { value: "graduatelandats", label: "Graduateland ATS" },
  { value: "graftonrecruitmentcrm", label: "Grafton Recruitment CRM" },
  { value: "greenhouse", label: "Greenhouse" },
  { value: "greenhousejapan", label: "Greenhouse Japan" },
  { value: "greenjapan", label: "Green Japan" },
  { value: "gulftalentmena", label: "GulfTalent MENA" },
  { value: "gupyadmissao", label: "Gupy Admissao" },
  { value: "gupybrazil", label: "Gupy Brazil" },
  { value: "hackerearthindia", label: "HackerEarth India" },
  { value: "hackerearthrecruit", label: "HackerEarth Recruit" },
  { value: "hackertrailplatform", label: "HackerTrail Platform" },
  { value: "hansenats", label: "Hansen ATS" },
  { value: "harveynashcrm", label: "Harvey Nash CRM" },
  { value: "haufe", label: "Haufe" },
  { value: "haufetalentgermany", label: "Haufe Talent Germany" },
  { value: "haystalentsolutions", label: "Hays Talent Solutions" },
  { value: "heidrickstruggles", label: "Heidrick Struggles" },
  { value: "heuronsindia", label: "Heurons India" },
  { value: "hhaexchangerecruiting", label: "HHAeXchange Recruiting" },
  { value: "hibob", label: "HiBob" },
  { value: "highermeats", label: "HigherMe ATS" },
  { value: "himalayas", label: "Himalayas" },
  { value: "hirebridge", label: "Hirebridge" },
  { value: "hired", label: "Hired" },
  { value: "hiredsingapore", label: "Hired Singapore" },
  { value: "hireflix", label: "Hireflix" },
  { value: "hirehive", label: "HireHive" },
  { value: "hireland", label: "Hireland" },
  { value: "hireroadrecruiting", label: "Hireroad Recruiting" },
  { value: "hireserve", label: "Hireserve" },
  { value: "hiretrace", label: "Hiretrace" },
  { value: "hirex", label: "Hirex" },
  { value: "hirexturkey", label: "Hirex Turkey" },
  { value: "hiringbrazil", label: "Hiring Brazil" },
  { value: "hiringjapan", label: "Hiring Japan" },
  { value: "hiringmx", label: "Hiring MX" },
  { value: "hiringonboardaustralia", label: "HiringOnboard Australia" },
  { value: "hiringopps", label: "HiringOpps" },
  { value: "hiringsg", label: "Hiring SG" },
  { value: "hiringteam", label: "HiringTeam" },
  { value: "hiringthing", label: "HiringThing" },
  { value: "hiringua", label: "Hiring UA" },
  { value: "hkgoodjobs", label: "HKGoodJobs" },
  { value: "hoganassessments", label: "Hogan Assessments" },
  { value: "homecarepulsehr", label: "HomeCare Pulse HR" },
  { value: "horizonseor", label: "Horizons EOR" },
  { value: "hrmanagernowtalentech", label: "Hr-manager (now Talentech)" },
  { value: "hrmantra", label: "HRMantra" },
  { value: "hrmdirect", label: "HRMDirect" },
  { value: "hrmosjapan", label: "Hrmos Japan" },
  { value: "hronboardaustralia", label: "HROnboard Australia" },
  { value: "hrpeakturkey", label: "HRPeak Turkey" },
  { value: "hrportal", label: "HR-Portal" },
  { value: "hrsystemukraine", label: "HR-System Ukraine" },
  { value: "hrworks", label: "HRworks" },
  { value: "hrworksgermany", label: "HRworks Germany" },
  { value: "hudsonsingapore", label: "Hudson Singapore" },
  { value: "humahr", label: "Huma HR" },
  { value: "humi", label: "Humi" },
  { value: "hurmasystemukraine", label: "HURMA System Ukraine" },
  { value: "icims", label: "iCIMS" },
  { value: "idibu", label: "Idibu" },
  { value: "ikaihrturkey", label: "IKAI HR Turkey" },
  { value: "indeedaustralia", label: "Indeed Australia" },
  { value: "infojobsinfoempleo", label: "Infojobs Infoempleo" },
  { value: "infortalentacquisition", label: "Infor Talent Acquisition" },
  { value: "inrecruit", label: "In-Recruit" },
  { value: "inrecruiting", label: "Inrecruiting" },
  { value: "insightglobalportal", label: "Insight Global Portal" },
  { value: "insperityrecruiting", label: "Insperity Recruiting" },
  { value: "intellihrplatform", label: "IntelliHR Platform" },
  { value: "intelycarerecruiting", label: "IntelyCare Recruiting" },
  { value: "intersearchportal", label: "InterSearch Portal" },
  { value: "intersearchsingapore", label: "InterSearch Singapore" },
  { value: "interviewerai", label: "Interviewer.ai" },
  { value: "interviewsjapan", label: "Interviews Japan" },
  { value: "intervueio", label: "Intervue.io" },
  { value: "invenias", label: "Invenias" },
  { value: "ismartrecruit", label: "iSmartRecruit" },
  { value: "isolvisolvedhire", label: "isolvedhire" },
  { value: "jacobrecruiting", label: "Jacob Recruiting" },
  { value: "jazzhr", label: "JazzHR" },
  { value: "jisrsaudiarabia", label: "Jisr Saudi Arabia" },
  { value: "jobadder", label: "JobAdder" },
  { value: "jobaffinity", label: "JobAffinity" },
  { value: "jobaps", label: "JobAps" },
  { value: "jobbermannigeria", label: "Jobberman Nigeria" },
  { value: "jobcanjapan", label: "Jobcan Japan" },
  { value: "jobconectado", label: "Job Conectado" },
  { value: "jobdiva", label: "JobDiva" },
  { value: "jobfinderpoland", label: "Jobfinder Poland" },
  { value: "jobijobaats", label: "Jobijoba ATS" },
  { value: "jobilla", label: "Jobilla" },
  { value: "jobma", label: "Jobma" },
  { value: "jobmarkethongkong", label: "JobMarket Hong Kong" },
  { value: "jobnakturkey", label: "Jobnak Turkey" },
  { value: "joboolo", label: "Joboolo" },
  { value: "jobrapidoats", label: "Jobrapido ATS" },
  { value: "jobsbgats", label: "Jobs.bg ATS" },
  { value: "jobschats", label: "Jobs.ch ATS" },
  { value: "jobscience", label: "Jobscience" },
  { value: "jobsciencerecruiting", label: "Jobscience Recruiting" },
  { value: "jobsdbhongkong", label: "JobsDB Hong Kong" },
  { value: "jobsdbsingapore", label: "JobsDB Singapore" },
  { value: "jobsoid", label: "Jobsoid" },
  { value: "jobstairs", label: "JobStairs" },
  { value: "jobstreetsingapore", label: "JobStreet Singapore" },
  { value: "jobtool", label: "Jobtool" },
  { value: "jobvite", label: "Jobvite" },
  { value: "jobwaremanager", label: "Jobware Manager" },
  { value: "jobylon", label: "Jobylon" },
  { value: "jobylonsweden", label: "Jobylon Sweden" },
  { value: "join", label: "JOIN" },
  { value: "joobleats", label: "Jooble ATS" },
  { value: "joraaustralia", label: "Jora Australia" },
  { value: "jugglehire", label: "Juggle Hire" },
  { value: "juiceboxai", label: "Juicebox.ai" },
  { value: "justworkspeo", label: "Justworks PEO" },
  { value: "k12jobspot", label: "K12JobSpot" },
  { value: "kandidatnet", label: "Kandidatnet" },
  { value: "karattech", label: "Karat Tech" },
  { value: "karieragrats", label: "Kariera.gr ATS" },
  { value: "karieraskats", label: "Kariera.sk ATS" },
  { value: "kariyernetats", label: "Kariyer.net ATS" },
  { value: "karriereatats", label: "Karriere.at ATS" },
  { value: "kawaderqatar", label: "Kawader Qatar" },
  { value: "kekaindia", label: "Keka India" },
  { value: "kellyservicesportal", label: "Kelly Services Portal" },
  { value: "kenjo", label: "Kenjo" },
  { value: "kenjo_new", label: "Kenjo" },
  { value: "kenjospain", label: "Kenjo Spain" },
  { value: "kenobynowgupy", label: "Kenoby (now Gupy)" },
  { value: "kerryconsulting", label: "Kerry Consulting" },
  { value: "kforceportal", label: "Kforce Portal" },
  { value: "kiwihr", label: "KiwiHR" },
  { value: "kolayik", label: "Kolay İK" },
  { value: "kooltlatam", label: "Koolt LatAm" },
  { value: "kornferryrecruit", label: "Korn Ferry Recruit" },
  { value: "krakowrecruiting", label: "Krakow Recruiting" },
  { value: "krowdyperu", label: "Krowdy Peru" },
  { value: "labasoftware", label: "Laba Software" },
  { value: "lanopayroll", label: "Lano Payroll" },
  { value: "larsrecruiting", label: "Lars Recruiting" },
  { value: "lever", label: "Lever" },
  { value: "linkedinapac", label: "LinkedIn APAC" },
  { value: "livaatrecruiting", label: "Livaat Recruiting" },
  { value: "lmcgiganowalmacareer", label: "LMC Giga (now Alma Career)" },
  { value: "logicmelon", label: "LogicMelon" },
  { value: "logiterahrflow", label: "Logitera HRflow" },
  { value: "loomrecruiting", label: "Loom Recruiting" },
  { value: "loxo", label: "Loxo" },
  { value: "luccafrance", label: "Lucca France" },
  { value: "lumesse", label: "Lumesse" },
  { value: "manatal", label: "Manatal" },
  { value: "manpowerportal", label: "Manpower Portal" },
  { value: "manpowersingapore", label: "Manpower Singapore" },
  { value: "matchboxrecruiting", label: "Matchbox Recruiting" },
  { value: "matchtechcrm", label: "Matchtech CRM" },
  { value: "maxhirenowbullhorn", label: "MaxHire (now Bullhorn)" },
  { value: "mcquaigtalent", label: "McQuaig Talent" },
  { value: "mephistorecruiting", label: "Mephisto Recruiting" },
  { value: "mercermettl", label: "Mercer Mettl" },
  { value: "mercermettlindia", label: "Mercer Mettl India" },
  { value: "mercuryxrm", label: "Mercury xRM" },
  { value: "meta4", label: "Meta4" },
  { value: "meteojobats", label: "Meteojob ATS" },
  { value: "mexicorecruiting", label: "Mexico Recruiting" },
  { value: "michaelpageportal", label: "Michael Page Portal" },
  { value: "milanomedienats", label: "Milano Medien ATS" },
  { value: "mitularecruiting", label: "Mitula Recruiting" },
  { value: "mokahrsingapore", label: "MokaHR Singapore" },
  { value: "monbewerbung", label: "MonBewerbung" },
  { value: "morsongroupportal", label: "Morson Group Portal" },
  { value: "multiplierhr", label: "Multiplier HR" },
  { value: "munichrecruiting", label: "Munich Recruiting" },
  { value: "murexrecruiting", label: "Murex Recruiting" },
  { value: "mycareersfuture", label: "MyCareersFuture" },
  { value: "myinterview", label: "MyInterview" },
  { value: "mynavitenshoku", label: "Mynavi Tenshoku" },
  { value: "myrecruitmentplusaustralia", label: "MyRecruitmentPlus Australia" },
  { value: "n2growthportal", label: "N2Growth Portal" },
  { value: "nabbeshuae", label: "Nabbesh UAE" },
  { value: "namelyhr", label: "Namely HR" },
  { value: "naukrirms", label: "Naukri RMS" },
  { value: "neogov", label: "NEOGOV" },
  { value: "nesfircroftcrm", label: "NES Fircroft CRM" },
  { value: "networx", label: "Networx" },
  { value: "networxats", label: "Networx ATS" },
  { value: "neuvootalentcom", label: "Neuvoo (Talent.com)" },
  { value: "nodeflairsingapore", label: "Nodeflair Singapore" },
  { value: "nordichr", label: "Nordic HR" },
  { value: "odgersberndtsonportal", label: "Odgers Berndtson Portal" },
  { value: "offerzensouthafrica", label: "OfferZen South Africa" },
  { value: "oleeo", label: "Oleeo" },
  { value: "omnipresentgroup", label: "Omnipresent Group" },
  { value: "oneclickrecruiting", label: "Oneclick Recruiting" },
  { value: "onerecruitaustralia", label: "OneRecruit Australia" },
  { value: "onlyfy", label: "Onlyfy" },
  { value: "oracle", label: "Oracle" },
  { value: "osensejapan", label: "Osense Japan" },
  { value: "ostendis", label: "Ostendis" },
  { value: "oysterhr", label: "Oyster HR" },
  { value: "pageexecutiveportal", label: "Page Executive Portal" },
  { value: "pageup", label: "PageUp" },
  { value: "panalytanalytics", label: "Panalyt Analytics" },
  { value: "pandapmxico", label: "Pandapé México" },
  { value: "papayaglobalhr", label: "Papaya Global HR" },
  { value: "paradox", label: "Paradox" },
  { value: "paramaiindia", label: "Param.ai India" },
  { value: "parisrecruiting", label: "Paris Recruiting" },
  { value: "paylocity", label: "Paylocity" },
  { value: "pcrecruiter", label: "PCRecruiter" },
  { value: "pennalhh", label: "Penna LHH" },
  { value: "peopleforce", label: "PeopleForce" },
  { value: "peopleforceukraine", label: "PeopleForce Ukraine" },
  { value: "perbilityhelix", label: "Perbility Helix" },
  { value: "persiahr", label: "PersiaHR" },
  { value: "persisbewerbermanagement", label: "Persis Bewerbermanagement" },
  { value: "persolkellyapac", label: "Persolkelly APAC" },
  { value: "personio", label: "Personio", enabledByDefault: false },
  { value: "petroplanportal", label: "Petroplan Portal" },
  { value: "peykhr", label: "Peyk HR" },
  { value: "phenom", label: "Phenom" },
  { value: "pingboardorg", label: "Pingboard Org" },
  { value: "pinpointhq", label: "PinpointHQ" },
  { value: "pitchnhire", label: "Pitch N Hire" },
  { value: "placementpartnersouthafrica", label: "Placement Partner South Africa" },
  { value: "pnetsouthafrica", label: "Pnet South Africa" },
  { value: "poachedhospitality", label: "Poached Hospitality" },
  { value: "policeapp", label: "PoliceApp" },
  { value: "pontahr", label: "PontaHR" },
  { value: "pontahrcroatia", label: "PontaHR Croatia" },
  { value: "pracaplats", label: "Praca.pl ATS" },
  { value: "pracujplats", label: "Pracuj.pl ATS" },
  { value: "prescreen", label: "Prescreen" },
  { value: "prescreenaustria", label: "Prescreen Austria" },
  { value: "prevuehr", label: "Prevue HR" },
  { value: "procvlabturkey", label: "ProCvLab Turkey" },
  { value: "profesiaatsbyalmacareer", label: "Profesia ATS (by Alma Career)" },
  { value: "profilesearch", label: "Profile Search" },
  { value: "prospectivemediaats", label: "Prospective Media ATS" },
  { value: "pyjamahr", label: "PyjamaHR" },
  { value: "qjumpersnewzealand", label: "QJumpers New Zealand" },
  { value: "qualifiedio", label: "Qualified.io" },
  { value: "quickin", label: "Quickin" },
  { value: "rabotauaats", label: "Rabota.ua ATS" },
  { value: "randstadportal", label: "Randstad Portal" },
  { value: "randstadsingapore", label: "Randstad Singapore" },
  { value: "rapidrecruit", label: "RapidRecruit" },
  { value: "reachmeenowtalentech", label: "ReachMee (now Talentech)" },
  { value: "recooty", label: "Recooty" },
  { value: "recruitcrm", label: "RecruitCRM" },
  { value: "recruitee", label: "Recruitee" },
  { value: "recruiteefrance", label: "Recruitee France" },
  { value: "recruiterboxtrakstar", label: "Recruiterbox Trakstar" },
  { value: "recruitercz", label: "Recruiter.cz" },
  { value: "recruiterde", label: "Recruiter.de" },
  { value: "recruiterturkey", label: "Recruiter Turkey" },
  { value: "recruitexpress", label: "Recruit Express" },
  { value: "recruitio", label: "Recruitio" },
  { value: "recruitive", label: "Recruitive" },
  { value: "recruitloopaustralia", label: "RecruitLoop Australia" },
  { value: "recruitopoland", label: "Recruito Poland" },
  { value: "recrutamentosimples", label: "Recrutamento Simples" },
  { value: "recrutimmo", label: "Recrutimmo" },
  { value: "reedglobalcrm", label: "Reed Global CRM" },
  { value: "reliasacademy", label: "Relias Academy" },
  { value: "remotecomrecruiting", label: "Remote.com recruiting" },
  { value: "remoteok", label: "RemoteOK" },
  { value: "retorio", label: "Retorio" },
  { value: "revelobrazil", label: "Revelo Brazil" },
  { value: "rexxsystemsrecruiting", label: "rexx systems Recruiting" },
  { value: "rikunabinext", label: "Rikunabi Next" },
  { value: "riorecruiting", label: "Rio Recruiting" },
  { value: "rippling", label: "Rippling" },
  { value: "risepeople", label: "Rise People" },
  { value: "roarrecruiting", label: "Roar Recruiting" },
  { value: "roberthalfsingapore", label: "Robert Half Singapore" },
  { value: "robertwalterscrm", label: "Robert Walters CRM" },
  { value: "runmyaccountsrecruiting", label: "Runmyaccounts Recruiting" },
  { value: "russellreynoldsportal", label: "Russell Reynolds Portal" },
  { value: "sabasoftware", label: "Saba Software" },
  { value: "sagehr", label: "SageHR" },
  { value: "sagepeoplerecruiting", label: "Sage People Recruiting" },
  { value: "salexrecruiting", label: "Salex Recruiting" },
  { value: "saopaulorecruiting", label: "Sao Paulo Recruiting" },
  { value: "saphrcloud", label: "SAP HR Cloud" },
  { value: "sapsuccessfactors", label: "SAP SuccessFactors" },
  { value: "sarirecruiting", label: "Sari Recruiting" },
  { value: "sarirecruitingbr", label: "Sari Recruiting BR" },
  { value: "schoolspring", label: "SchoolSpring" },
  { value: "seasonedrecruiting", label: "Seasoned Recruiting" },
  { value: "secretcvats", label: "Secretcv ATS" },
  { value: "seekaustralia", label: "Seek Australia" },
  { value: "seekout", label: "SeekOut" },
  { value: "semacnorway", label: "Semac Norway" },
  { value: "sendoutsnowbullhorn", label: "Sendouts (now Bullhorn)" },
  { value: "sentrient", label: "Sentrient" },
  { value: "sherlockhrlatam", label: "SherlockHR LatAm" },
  { value: "shiftkeyportal", label: "ShiftKey Portal" },
  { value: "shltalent", label: "SHL Talent" },
  { value: "shortlistindia", label: "Shortlist India" },
  { value: "siftdirectory", label: "Sift Directory" },
  { value: "signatureconsultants", label: "Signature Consultants" },
  { value: "signiumportal", label: "Signium Portal" },
  { value: "silkroadtechnology", label: "SilkRoad Technology" },
  { value: "simplicant", label: "Simplicant" },
  { value: "simplifyhrsouthafrica", label: "Simplify.hr South Africa" },
  { value: "singaporerecruiting", label: "Singapore Recruiting" },
  { value: "skeeled", label: "Skeeled" },
  { value: "skeeledluxembourg", label: "Skeeled Luxembourg" },
  { value: "skuademployment", label: "Skuad employment" },
  { value: "skyhiveskills", label: "Skyhive Skills" },
  { value: "skyrecruiting", label: "Sky Recruiting" },
  { value: "smartrecruiters", label: "SmartRecruiters" },
  { value: "smartsearch", label: "SmartSearch" },
  { value: "smartstartaustralia", label: "SmartStart Australia" },
  { value: "snagajobpeoplematter", label: "Snagajob PeopleMatter" },
  { value: "snaphirenewzealand", label: "SnapHire New Zealand" },
  { value: "softgardengermany", label: "Softgarden Germany" },
  { value: "softy", label: "Softy" },
  { value: "solidesats", label: "Solides ATS" },
  { value: "solomonpageportal", label: "Solomon Page Portal" },
  { value: "sonru", label: "Sonru" },
  { value: "spencerogdenportal", label: "Spencer Ogden Portal" },
  { value: "spencerstuartportal", label: "Spencer Stuart Portal" },
  { value: "sprocketsai", label: "Sprockets AI" },
  { value: "staffsuite", label: "Staffsuite" },
  { value: "stantonchaseportal", label: "Stanton Chase Portal" },
  { value: "statejobsny", label: "StateJobsNY" },
  { value: "sthreeplccrm", label: "SThree PLC CRM" },
  { value: "sumtotalsystems", label: "SumTotal Systems" },
  { value: "swiftworldwide", label: "Swift Worldwide" },
  { value: "sympa", label: "Sympa" },
  { value: "sympafinland", label: "Sympa Finland" },
  { value: "symphonytalent", label: "Symphony Talent" },
  { value: "talentadore", label: "Talentadore" },
  { value: "talentadorefinland", label: "TalentAdore Finland" },
  { value: "talentcloudjapan", label: "Talent Cloud Japan" },
  { value: "talentechsuite", label: "Talentech Suite" },
  { value: "talentera", label: "Talentera" },
  { value: "talenteramena", label: "Talentera MENA" },
  { value: "talentex", label: "Talentex" },
  { value: "talentiasoftware", label: "Talentia Software" },
  { value: "talentiojapan", label: "Talentio Japan" },
  { value: "talentlink", label: "Talentlink" },
  { value: "talentlyft", label: "Talentlyft" },
  { value: "talentlyftcroatia", label: "Talentlyft Croatia" },
  { value: "talentnest", label: "TalentNest" },
  { value: "talentomobi", label: "Talento.mobi" },
  { value: "talentplug", label: "Talentplug" },
  { value: "talentreef", label: "TalentReef" },
  { value: "talentsoft", label: "Talentsoft" },
  { value: "talentum", label: "Talentum" },
  { value: "talentvineaustralia", label: "TalentVine Australia" },
  { value: "talentwunder", label: "Talentwunder" },
  { value: "talentwundergermany", label: "Talentwunder Germany" },
  { value: "taleo", label: "Taleo" },
  { value: "talexio", label: "Talexio" },
  { value: "targetrecruit", label: "TargetRecruit" },
  { value: "tasheeluae", label: "Tasheel UAE" },
  { value: "tawteenuae", label: "Tawteen UAE" },
  { value: "teamiobyalmacareer", label: "Teamio (by Alma Career)" },
  { value: "teamtailor", label: "Teamtailor" },
  { value: "tecolocoempresas", label: "Tecoloco Empresas" },
  { value: "tempworks", label: "TempWorks" },
  { value: "testgorillaplatform", label: "TestGorilla Platform" },
  { value: "testportalsuite", label: "Testportal Suite" },
  { value: "theapplicantmanager", label: "The Applicant Manager" },
  { value: "thomasinternational", label: "Thomas International" },
  { value: "tokyorecruiting", label: "Tokyo Recruiting" },
  { value: "tracker", label: "Tracker" },
  { value: "trackersouthafrica", label: "Tracker South Africa" },
  { value: "traffitpoland", label: "TRAFFIT Poland" },
  { value: "transearchportal", label: "Transearch Portal" },
  { value: "tribepad", label: "Tribepad" },
  { value: "tribepadats", label: "Tribepad ATS" },
  { value: "triorecruitment", label: "Trio Recruitment" },
  { value: "trovitrecruiting", label: "Trovit Recruiting" },
  { value: "turbohire", label: "TurboHire" },
  { value: "turirecruiting", label: "Turi Recruiting" },
  { value: "ultipro", label: "UltiPro" },
  { value: "unit4talentmanagement", label: "UNIT4 Talent Management" },
  { value: "usajobs", label: "USAJobs" },
  { value: "vacancyfiller", label: "Vacancy Filler" },
  { value: "vagascombr", label: "Vagas.com.br" },
  { value: "vagasforbusiness", label: "Vagas For Business" },
  { value: "varbinowgrade", label: "Varbi (now Grade)" },
  { value: "velocityglobaleor", label: "Velocity Global EOR" },
  { value: "veredusportal", label: "Veredus Portal" },
  { value: "vervoeats", label: "Vervoe ATS" },
  { value: "vibbn", label: "Vibbn" },
  { value: "vidcruitersuite", label: "VidCruiter Suite" },
  { value: "viennarecruiting", label: "Vienna Recruiting" },
  { value: "vireup", label: "Vireup" },
  { value: "vivahr", label: "VIVAHR" },
  { value: "vividresourcing", label: "Vivid Resourcing" },
  { value: "vizyonhr", label: "Vizyon HR" },
  { value: "vultus", label: "Vultus" },
  { value: "vurvnowtaleo", label: "Vurv (now Taleo)" },
  { value: "vurvtechnology", label: "Vurv Technology" },
  { value: "wantedlyjapan", label: "Wantedly Japan" },
  { value: "wardhowellportal", label: "Ward Howell Portal" },
  { value: "warpproxyats", label: "Warp Proxy ATS" },
  { value: "warsawrecruiting", label: "Warsaw Recruiting" },
  { value: "wazzufegypt", label: "Wazzuf Egypt" },
  { value: "webcruiternorway", label: "Webcruiter Norway" },
  { value: "webrecruit", label: "Webrecruit" },
  { value: "webrecruitsoftware", label: "Webrecruit software" },
  { value: "wehire", label: "WeHire" },
  { value: "wellskycareport", label: "WellSky CarePort" },
  { value: "willo", label: "Willo" },
  { value: "willovideo", label: "Willo Video" },
  { value: "wocoats", label: "WoCo ATS" },
  { value: "woffurecruiting", label: "Woffu Recruiting" },
  { value: "workable", label: "Workable", enabledByDefault: false },
  { value: "workday", label: "Workday" },
  { value: "workmotionhr", label: "Workmotion HR" },
  { value: "workstreamhr", label: "Workstream HR" },
  { value: "workuaats", label: "Work.ua ATS" },
  { value: "wovenassessments", label: "Woven Assessments" },
  { value: "yenibirisats", label: "Yenibiris ATS" },
  { value: "youthallats", label: "Youthall ATS" },
  { value: "zalarisrecruiting", label: "Zalaris Recruiting" },
  { value: "zapaplatabgats", label: "Zapaplata.bg ATS" },
  { value: "zarpe", label: "Zarpe" },
  { value: "zenhrjordan", label: "ZenHR Jordan" },
  { value: "zoho", label: "Zoho Recruit" },
  { value: "zookeep", label: "Zookeep" }
]);
const ATS_FILTER_OPTIONS = new Set(ATS_FILTER_OPTION_ITEMS.map((item) => item.value));
const ATS_FILTER_LABEL_BY_VALUE = new Map(ATS_FILTER_OPTION_ITEMS.map((item) => [item.value, item.label]));
const SYNC_DEFAULT_ENABLED_ATS = Object.freeze(
  ATS_FILTER_OPTION_ITEMS
    .filter((item) => item.enabledByDefault !== false && isAtsEnabledByDefault(item.value))
    .map((item) => item.value)
);

const ATS_FILTER_ALIASES = new Map([
  ["ashbyhq", "ashby"],
  ["greenhouseio", "greenhouse"],
  ["greenhouse.io", "greenhouse"],
  ["leverco", "lever"],
  ["lever.co", "lever"],
  ["recruiteecom", "recruitee"],
  ["recruitee.com", "recruitee"],
  ["ukg", "ultipro"],
  ["taleonet", "taleo"],
  ["taleo.net", "taleo"],
  ["jobvitecom", "jobvite"],
  ["jobvite.com", "jobvite"],
  ["applicantprocom", "applicantpro"],
  ["applicantpro.com", "applicantpro"],
  ["hibob.com", "hibob"],
  ["hibobcom", "hibob"],
  ["hibob", "hibob"],
  ["careers.hibob.com", "hibob"],
  ["careershibobcom", "hibob"],
  ["isolvisolvedhire", "isolvisolvedhire"],
  ["isolvedhire", "isolvisolvedhire"],
  ["isolvedhire.com", "isolvisolvedhire"],
  ["isolvedhirecom", "isolvisolvedhire"],
  ["applytojobcom", "applytojob"],
  ["applytojob.com", "applytojob"],
  ["icimscom", "icims"],
  ["icims.com", "icims"],
  ["theapplicantmanagercom", "theapplicantmanager"],
  ["theapplicantmanager.com", "theapplicantmanager"],
  ["breezyhr", "breezy"],
  ["breezy.hr", "breezy"],
  ["breezyhrcom", "breezy"],
  ["zohorecruit", "zoho"],
  ["zohorecruit.com", "zoho"],
  ["zohorecruitcom", "zoho"],
  ["applicantai.com", "applicantai"],
  ["applicantaicom", "applicantai"],
  ["bamboohr.com", "bamboohr"],
  ["bamboohrcom", "bamboohr"],
  ["careerplug.com", "careerplug"],
  ["careerplugcom", "careerplug"],
  ["manatal.com", "manatal"],
  ["manatalcom", "manatal"],
  ["careers-page.com", "manatal"],
  ["careerspagecom", "manatal"],
  ["careerpuck.com", "careerpuck"],
  ["careerpuckcom", "careerpuck"],
  ["dayforcehcm", "dayforcehcm"],
  ["dayforce", "dayforcehcm"],
  ["dayforcehcm.com", "dayforcehcm"],
  ["dayforcehcmcom", "dayforcehcm"],
  ["fountain.com", "fountain"],
  ["fountaincom", "fountain"],
  ["getro.com", "getro"],
  ["getrocom", "getro"],
  ["governmentjobs.com", "governmentjobs"],
  ["governmentjobscom", "governmentjobs"],
  ["governmentjobs", "governmentjobs"],
  ["smartrecruiters.com", "smartrecruiters"],
  ["smartrecruiterscom", "smartrecruiters"],
  ["jobs.smartrecruiters.com", "smartrecruiters"],
  ["jobssmartrecruiterscom", "smartrecruiters"],
  ["smartrecruiters", "smartrecruiters"],
  ["policeapp", "policeapp"],
  ["policeapp.com", "policeapp"],
  ["policeappcom", "policeapp"],
  ["www.policeapp.com", "policeapp"],
  ["wwwpoliceappcom", "policeapp"],
  ["usajobs", "usajobs"],
  ["usajobs.gov", "usajobs"],
  ["usajobsgov", "usajobs"],
  ["www.usajobs.gov", "usajobs"],
  ["wwwusajobsgov", "usajobs"],
  ["k12jobspot", "k12jobspot"],
  ["k12jobspot.com", "k12jobspot"],
  ["k12jobspotcom", "k12jobspot"],
  ["www.k12jobspot.com", "k12jobspot"],
  ["wwwk12jobspotcom", "k12jobspot"],
  ["api.k12jobspot.com", "k12jobspot"],
  ["apik12jobspotcom", "k12jobspot"],
  ["schoolspring", "schoolspring"],
  ["schoolspring.com", "schoolspring"],
  ["schoolspringcom", "schoolspring"],
  ["api.schoolspring.com", "schoolspring"],
  ["apischoolspringcom", "schoolspring"],
  ["www.schoolspring.com", "schoolspring"],
  ["wwwschoolspringcom", "schoolspring"],
  ["calcareers", "calcareers"],
  ["calcareers.ca.gov", "calcareers"],
  ["calcareerscagov", "calcareers"],
  ["www.calcareers.ca.gov", "calcareers"],
  ["wwwcalcareerscagov", "calcareers"],
  ["calopps", "calopps"],
  ["calopps.org", "calopps"],
  ["caloppsorg", "calopps"],
  ["www.calopps.org", "calopps"],
  ["wwwcaloppsorg", "calopps"],
  ["statejobsny", "statejobsny"],
  ["statejobsny.com", "statejobsny"],
  ["statejobsnycom", "statejobsny"],
  ["www.statejobsny.com", "statejobsny"],
  ["wwwstatejobsnycom", "statejobsny"],
  ["hrmdirect.com", "hrmdirect"],
  ["hrmdirectcom", "hrmdirect"],
  ["talentlyft.com", "talentlyft"],
  ["talentlyftcom", "talentlyft"],
  ["talexio.com", "talexio"],
  ["talexiocom", "talexio"],
  ["teamtailor.com", "teamtailor"],
  ["teamtailorcom", "teamtailor"],
  ["freshteam.com", "freshteam"],
  ["freshteamcom", "freshteam"],
  ["sagehr", "sagehr"],
  ["sage.hr", "sagehr"],
  ["talent.sage.hr", "sagehr"],
  ["talentsagehr", "sagehr"],
  ["loxo.co", "loxo"],
  ["loxoco", "loxo"],
  ["app.loxo.co", "loxo"],
  ["apploxoco", "loxo"],
  ["peopleforce.io", "peopleforce"],
  ["peopleforceio", "peopleforce"],
  ["simplicant.com", "simplicant"],
  ["simplicantcom", "simplicant"],
  ["pinpointhq.com", "pinpointhq"],
  ["pinpointhqcom", "pinpointhq"],
  ["recruitcrm.io", "recruitcrm"],
  ["recruitcrmiocom", "recruitcrm"],
  ["recruitcrmio", "recruitcrm"],
  ["rippling.com", "rippling"],
  ["ripplingcom", "rippling"],
  ["ats.rippling.com", "rippling"],
  ["atsripplingcom", "rippling"],
  ["rippling", "rippling"],
  ["jobs.gem.com", "gem"],
  ["gem.com", "gem"],
  ["gemcom", "gem"],
  ["jobapscloud.com", "jobaps"],
  ["jobapscloudcom", "jobaps"],
  ["join.com", "join"],
  ["joincom", "join"],
  ["jobappnetwork.com", "talentreef"],
  ["jobappnetworkcom", "talentreef"],
  ["apply.jobappnetwork.com", "talentreef"],
  ["applyjobappnetworkcom", "talentreef"],
  ["saphrcloud", "saphrcloud"],
  ["saphrcloud.com", "saphrcloud"],
  ["saphrcloudcom", "saphrcloud"],
  ["jobs.hr.cloud.sap", "saphrcloud"],
  ["jobshrcloudsap", "saphrcloud"],
  ["adp_myjobs", "adp_myjobs"],
  ["adpmyjobs", "adp_myjobs"],
  ["adp_workforcenow", "adp_workforcenow"],
  ["adpworkforcenow", "adp_workforcenow"],
  ["workforcenow.adp.com", "adp_workforcenow"],
  ["workforcenowadpcom", "adp_workforcenow"],
  ["careerspage", "careerspage"],
  ["careerspage.io", "careerspage"],
  ["careerspageio", "careerspage"],
  ["paylocity", "paylocity"],
  ["paylocity.com", "paylocity"],
  ["paylocitycom", "paylocity"],
  ["recruiting.paylocity.com", "paylocity"],
  ["recruitingpaylocitycom", "paylocity"],
  ["personio", "personio"],
  ["personio.de", "personio"],
  ["personiode", "personio"],
  ["jobs.personio.de", "personio"],
  ["jobspersoniode", "personio"],
  ["workable", "workable"],
  ["workable.com", "workable"],
  ["workablecom", "workable"],
  ["apply.workable.com", "workable"],
  ["applyworkablecom", "workable"],
  ["eightfold", "eightfold"],
  ["eightfold.ai", "eightfold"],
  ["eightfoldai", "eightfold"],
  ["pageup", "pageup"],
  ["pageuppeople", "pageup"],
  ["pageuppeople.com", "pageup"],
  ["pageuppeoplecom", "pageup"],
  ["careers.pageuppeople.com", "pageup"],
  ["careerspageuppeoplecom", "pageup"],
  ["oracle", "oracle"],
  ["oraclecloud", "oracle"],
  ["oraclecloud.com", "oracle"],
  ["oraclecloudcom", "oracle"],
  ["hirebridge", "hirebridge"],
  ["hirebridge.com", "hirebridge"],
  ["hirebridgecom", "hirebridge"],
  ["recruit.hirebridge.com", "hirebridge"],
  ["recruithirebridgecom", "hirebridge"],
  ["brassring", "brassring"],
  ["brassring.com", "brassring"],
  ["brassringcom", "brassring"],
  ["sjobs.brassring.com", "brassring"],
  ["sjobsbrassringcom", "brassring"],
  ["applitrack.com", "applitrack"],
  ["applitrackcom", "applitrack"],
  ["applitrack", "applitrack"]
]);

function normalizeLikeText(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ");
}

function normalizeStringArray(value) {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => String(item || "").trim())
    .filter(Boolean);
}

function parseStringArrayInput(value) {
  if (Array.isArray(value)) return normalizeStringArray(value);
  try {
    const parsed = JSON.parse(String(value || "[]"));
    return normalizeStringArray(Array.isArray(parsed) ? parsed : []);
  } catch {
    return [];
  }
}

function normalizeAtsFilterValue(value) {
  const normalized = normalizeLikeText(value);
  return ATS_FILTER_ALIASES.get(normalized) || normalized;
}

function getAtsFilterAliasValues(value) {
  const canonical = normalizeAtsFilterValue(value);
  if (!canonical) return [];
  const aliases = new Set([canonical]);
  for (const [alias, target] of ATS_FILTER_ALIASES.entries()) {
    if (target === canonical) aliases.add(alias);
  }
  return Array.from(aliases);
}

function quotePostgresLiteral(value) {
  return `'${String(value || "").replace(/'/g, "''")}'`;
}

function buildPostgresAtsFilterCanonicalExpression(columnSql) {
  const column = String(columnSql || "").trim();
  if (!column) throw new Error("columnSql is required");
  const normalizedColumn = `LOWER(BTRIM(${column}))`;
  const cases = [];
  for (const [alias, target] of ATS_FILTER_ALIASES.entries()) {
    if (!alias || !target || alias === target) continue;
    cases.push(`WHEN ${quotePostgresLiteral(alias)} THEN ${quotePostgresLiteral(target)}`);
  }
  return `(CASE ${normalizedColumn} ${cases.join(" ")} ELSE ${normalizedColumn} END)`;
}

function normalizeAtsFilters(value) {
  const items = normalizeStringArray(Array.isArray(value) ? value : [value])
    .map((item) => normalizeAtsFilterValue(item))
    .filter((item) => ATS_FILTER_OPTIONS.has(item));
  return Array.from(new Set(items));
}

function normalizeSyncEnabledAts(value, fallbackValue = SYNC_DEFAULT_ENABLED_ATS) {
  const activeOnly = (items) => items.filter((item) => isAtsEnabledByDefault(item));
  const fallback = activeOnly(normalizeAtsFilters(Array.isArray(fallbackValue) ? fallbackValue : SYNC_DEFAULT_ENABLED_ATS));
  const requested = normalizeAtsFilters(Array.isArray(value) ? value : parseStringArrayInput(value));
  const normalized = activeOnly(requested);
  if (normalized.length > 0) return normalized;
  if (requested.length > 0) return [];
  if (fallback.length > 0) return fallback;
  return Array.from(SYNC_DEFAULT_ENABLED_ATS);
}

module.exports = {
  ATS_FILTER_LABEL_BY_VALUE,
  ATS_FILTER_OPTION_ITEMS,
  ATS_FILTER_OPTIONS,
  SYNC_DEFAULT_ENABLED_ATS,
  buildPostgresAtsFilterCanonicalExpression,
  getAtsFilterAliasValues,
  normalizeAtsFilterValue,
  normalizeAtsFilters,
  normalizeSyncEnabledAts
};
